name: hand-control
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyzmq=27.0.1
  - readline=8.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
      - absl-py==2.3.1
      - attrs==25.3.0
      - cffi==1.17.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - flatbuffers==25.2.10
      - fonttools==4.59.1
      - jax==0.7.0
      - jaxlib==0.7.0
      - kiwisolver==1.4.9
      - matplotlib==3.10.5
      - mediapipe==0.10.21
      - ml-dtypes==0.5.3
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - pillow==11.3.0
      - protobuf==4.25.8
      - pycparser==2.22
      - pyparsing==3.2.3
      - scipy==1.16.1
      - sentencepiece==0.2.1
      - sounddevice==0.5.2
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/mediapipe
